feat: upgrade support to mongo v7
SvanBoxel/organization-workflows pull request #51
Opened 2024-04-25 20:34 UTC by caioq

## Why

The current version of mongoose (v5) doesn't support the new versions of mongodb.

## What

- Upgrade mongooose to v8
- Upgrade typescript to v5

2024-04-26 17:57 UTC, caioq commented
@SvanBoxel can you help me with a review?

2024-04-29 14:52 UTC, SvanBoxel approved these changes

2024-04-29 14:52 UTC, SvanBoxel requested changes
Could you undo all the linting changes and/or make them part of a separate PR?

2024-04-29 17:55 UTC, caioq commented
> Could you undo all the linting changes and/or make them part of a separate PR?

Sure! I undid some format linting changes, is that your request?
I had to upgrade the eslint, node and typescript dependencies because some conflict with the new version of the mongoose dependency.

2024-04-30 07:25 UTC, SvanBoxel commented
Hey, I still see a lot of formatting changes. I hope we can keep the scope of this PR to the upgrade of the packages without changing the rules that are applied to the code.

2024-04-30 12:23 UTC, caioq commented
> Hey, I still see a lot of formatting changes. I hope we can keep the scope of this PR to the upgrade of the packages without changing the rules that are applied to the code.

Hi! I had a hard time undoing some formatting changes due to different rules applied to parts of the code, but now I think I managed it completely. 
Then I can open a new PR to establish a formatting rule throughout the code base

2024-04-30 13:35 UTC, SvanBoxel commented
Thank you, that already makes reviewing a bit easier. I also noticed you added a bunch of `console.debug` statements? Are those needed as part of this PR?

2024-04-30 14:23 UTC, caioq commented
> Thank you, that already makes reviewing a bit easier. I also noticed you added a bunch of `console.debug` statements? Are those needed as part of this PR?

I added it to make debugging the application easier. I can remove them if you think it's better.

2024-04-30 15:02 UTC, SvanBoxel commented
For this PR, let's limit it to upgrading the packages. If you think other improvements can be made, it's best to propose those in separate PRs. Besides that it looks good to me! Thank you for working on this.

2024-04-30 16:11 UTC, caioq commented
> For this PR, let's limit it to upgrading the packages. If you think other improvements can be made, it's best to propose those in separate PRs. Besides that it looks good to me! Thank you for working on this.

Thanks! 
I have removed the debug logs here https://github.com/SvanBoxel/organization-workflows/pull/51/commits/04c61ac5bed5bfbded473196fc541e7d4c472447

2024-04-30 17:08 UTC, SvanBoxel approved these changes

2024-04-30 17:08 UTC, SvanBoxel commented on src/handlers/re-run.ts
> +  console.debug('Handling Re run event')
Do we need this console.debug as part of this PR?

2024-04-30 17:08 UTC, SvanBoxel commented on src/handlers/push.ts
> +  console.debug('Event dispatched', config.workflows_repository, JSON.stringify(data), JSON.stringify(response))
Do we need this console.debug as part of this PR?

2024-04-30 17:08 UTC, SvanBoxel commented on src/handlers/push.ts
> +  console.debug('Handling push event', context.payload.repository.name)
Do we need this console.debug as part of this PR?

2024-04-30 19:19 UTC, merged

2024-04-30 19:21 UTC, SvanBoxel commented
Published as pre-release: https://github.com/SvanBoxel/organization-workflows/releases/tag/1.5.0